apiVersion: extensions/v1beta1
kind: ReplicaSet 
metadata: 
  name: mysql-rs
  labels: 
    app: wordpress
spec:  
  replicas: 1 
  selector:  
    matchLabels: 
      app: wordpress
      tier: mysql
  template:  
    metadata: 
      labels:  
        app: wordpress
        tier: mysql
    spec:  
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc1
      containers:  
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass 
              key: password 
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:  
        - containerPort: 3306
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
          #
